parsers:
  doc_parser:
    engine: "unstructured"
    langs: ["en", "zh"]
  docx_parser:
    engine: "unstructured"
    langs: ["en", "zh"]
  epub_parser:
    engine: "unstructured"
    langs: ["en", "zh"]
  html_parser:
    engine: "unstructured"
    langs: ["en", "zh"]
  url_parser:
    engine: "jina"
    langs: ["en", "zh"]
  pdf_parser:
    engine: "marker"
    langs: ["en", "zh"]
  pptx_parser:
    engine: "unstructured"
    langs: ["en", "zh"]
  voice_parser:
    # option 1: use openai whisper api
    # engine: "openai_whisper_api"
    # api_base: "https://api.openai.com/v1"
    # api_key: "your_api_key"
    # model: "whisper"

    # option 2: use local whisper model
    engine: "openai_whisper_local"
    model: "large" # available models: https://github.com/openai/whisper#available-models-and-languages

converter:
  text_converter:
    engine: "litellm"
    model: "deepseek/deepseek-chat"
    api_key: "your_api_key"
    # base_url: ""
  image_converter:
    engine: "litellm"
    model: "gpt-4o-mini"
    api_key: "your_api_key"
    # base_url: ""
